<?php
/*
 * Mail Script
 * To Be used with Solomon's Login Script 
 *
 *
 * Author: Serubin323 (Solomon Rubin)
 * Version: 1.0 - beta/dev
 * Do not distribute
 *
 *
 *
 * The following should not be touched unless you know what your doing, even then, don't.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */
 
require_once './class.phpmailer.php';
define('GUSER', 'noreply@serubin.net'); // GMail username
define('GPWD', 'tntBlack!'); // GMail password

define('master', '
<div style="height:47px;width:100%;background:#d9d9d9;border-bottom:#c0c0c0 solid 1px;">
</div>
<div style="margin:25px auto;">
	%BODY%
</div>
<div style="background:#454546;width:100%;height:49px;color:#aaa;">
<p style="padding:10px;">This message was automaticly generated by <a style="color:#f7f7f7;border-bottom:1px #f7f7f7 dashed;text-decoration:none;" href="mindcloud.io">Mindcloud.io</a>. To <a href="mindcloud.io/preference">click here to unsubscribe</a>
</div>');

class mail{
	 
	function mailer($to, $from, $from_name, $subject, $body, $master) { 
		global $error;
		$mail = new PHPMailer();  // create a new object
		$mail->IsSMTP(); // enable SMTP
		$mail->SMTPDebug = 0;  // debugging: 1 = errors and messages, 2 = messages only
		$mail->SMTPAuth = true;  // authentication enabled
		$mail->SMTPSecure = 'ssl'; // secure transfer enabled REQUIRED for GMail
		$mail->Host = 'smtp.gmail.com';
		$mail->Port = 465; 
		$mail->Username = GUSER;  
		$mail->Password = GPWD;           
		$mail->IsHTML(true); 
		$mail->SetFrom($from, $from_name);
		$mail->Subject = $subject;
		$mail->Body = str_replace('%BODY%',$body,$master);
		$mail->AddAddress($to);
		if(!$mail->Send()) {
			return false;
		} else {
			return true;
		}
	}

	function send($email, $subject, $body){
		return mailer($email,"noreply@serubin.net","Mindcould - No Reply", $subject, $body, master);		
	}
}
?>