<?php
/*
 * Mail Script
 * To Be used with Solomon's Login Script 
 *
 *
 * Author: Serubin323 (Solomon Rubin)
 * Version: 1.0 - beta/dev
 * Do not distribute
 *
 *
 *
 * The following should not be touched unless you know what your doing, even then, don't.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */
 
require_once './include/mail/class.phpmailer.php';
define('GUSER', 'mindcloud@serubin.net'); // GMail username
define('GPWD', 'Lgc8Pn7LCyQmcjM4reZmVcxvxSExt7Ye'); // GMail password

define('master', '
<div style="height:45px;width:100%;background:#4754a4;">
	<a id="home-link" href="http://mindcloud.io/dashboard" target="_blank" ><img width="150px" class="logo-mini" src="https://mindcloud.io/assets/images/logo/logo_nav.png"></a>
</div>
<div style="margin:25px auto;">
	%BODY%
</div>
<div>
<hr/>
<p style="padding:0 10px;">This message was automatically generated by <a style="border-bottom:1px #ccc dashed;text-decoration:none;color:#3f51b5;" href="http://mindcloud.io">mindcloud.io</a>. To <a style="border-bottom:1px #ccc dashed;text-decoration:none;color:#3f51b5;" href="http://mindcloud.io/user/settings/unsubscribe">click here to unsubscribe</a>
</div>');

class Mail{

	private static function mailer($to, $from, $from_name, $subject, $body, $master) { 
		global $error;
		$mail = new PHPMailer();  // create a new object
		$mail->IsSMTP(); // enable SMTP
		$mail->SMTPDebug = 0;  // debugging: 1 = errors and messages, 2 = messages only
		$mail->SMTPAuth = true;  // authentication enabled
		$mail->SMTPSecure = 'ssl'; // secure transfer enabled REQUIRED for GMail
		$mail->Host = 'smtp.gmail.com';
		$mail->Port = 465; 
		$mail->Username = GUSER;  
		$mail->Password = GPWD;           
		$mail->IsHTML(true); 
		$mail->SetFrom($from, $from_name);
		$mail->Subject = $subject;
		$mail->Body = str_replace('%BODY%',$body,$master);
		if(is_array($to)){
			foreach($to as $email){
				$mail->AddAddress($email);
			}
		} else { 
			$mail->AddAddress($to);
		}
		if(!$mail->Send()) {
			return false;
		} else {
			return true;
		}
	}

	public static function send($email, $subject, $body){
		return Mail::mailer($email,"noreply@serubin.net","Mindcloud - No Reply", $subject, $body, master);
	}
}
?>
